server:
  port: 8081
  servlet:
    encoding:
      force-response: true

logging:
  level:
    com.boot.first: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-basic.ciq38khunuwi.ap-southeast-2.rds.amazonaws.com:3306/basic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: root1234

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      #show_sql: true
      #format_sql: true

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul